name: Build

on: push

jobs:
  now:
    runs-on: windows-2022
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Bump Version
        id: bump_version
        uses: Srlion/float-version-semantic@d71f36b2a2097a19d537d137e99eed9177ec60bd
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        shell: pwsh
        run: |
          .\build_shaders.bat
          python build.py ${{ steps.bump_version.outputs.new_tag }}
          copy src/rndx.lua C:\rndx.lua

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.bump_version.outputs.new_tag }}
          allowUpdates: true
          artifacts: C:\rndx.lua
